CREATE TABLE sales
(
    id         INT AUTO_INCREMENT PRIMARY KEY,
    title      VARCHAR(255) NOT NULL,
    content    VARCHAR(255) NOT NULL,
    type       VARCHAR(255) NOT NULL,
    date_from  VARCHAR(255) NOT NULL,
    date_to    VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
